name: build and test

on:
  push:
    branches: [ fork ]
  pull_request:
    branches: [ fork ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: go build -v ./...
    - run: go test -v ./...
