name: code coverage

on:
  push:
    branches: [ fork ]
  pull_request:
    branches: [ fork ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v1
    - name: calculate coverage
      run: go test -v -coverprofile=profile.cov ./...
    - name: send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
